version: 0.2

phases:
  build:
    commands:
      - echo "Preparing to deploy frontend to S3..."

  post_build:
    commands:
      - echo "Deploying frontend to S3..."
      - aws s3 sync Frontend/ s3://visiolex/frontend/ --delete --exclude "buildspec.yml"
      - echo "Done"